# Python Training
## Random User API

Remember the Get Methods that can be used to generate parameters. More info: [documentation](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01) page.

### Get Methods

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

### Example

In [46]:
#To start using the API you can install the randomuser library.
!pip install randomuser

Requirement already satisfied: randomuser in c:\users\filipe\anaconda3\lib\site-packages (1.6)

In [47]:
#Load the necessary libraries
from randomuser import RandomUser
import pandas as pd

In [48]:
#Create a random user object, r
r = RandomUser()

In [49]:
#Using generate_users() function, we get a list of random 10 users
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x1d59c293790>,
 <randomuser.RandomUser at 0x1d59c293d90>,
 <randomuser.RandomUser at 0x1d59c293430>,
 <randomuser.RandomUser at 0x1d59c293610>,
 <randomuser.RandomUser at 0x1d59c2933d0>,
 <randomuser.RandomUser at 0x1d59c2931f0>,
 <randomuser.RandomUser at 0x1d59c293bb0>,
 <randomuser.RandomUser at 0x1d59c293400>,
 <randomuser.RandomUser at 0x1d59c293730>,
 <randomuser.RandomUser at 0x1d59c293b80>]

The "Get Methods" functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call get_full_name() function.

In [50]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [51]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Glen Peck   glen.peck@example.com
Nikolas Appelt   nikolas.appelt@example.com
Sophie Wilson   sophie.wilson@example.com
Iker Ferrer   iker.ferrer@example.com
Monica Johnston   monica.johnston@example.com
Katherine Lord   katherine.lord@example.com
Andreas Johansen   andreas.johansen@example.com
Eloane Rey   eloane.rey@example.com
Isla Hatala   isla.hatala@example.com
Nolan Bishop   nolan.bishop@example.com

___

### Exercise 1

Generate photos of the random 5 users.

In [52]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/89.jpg
https://randomuser.me/api/portraits/men/8.jpg
https://randomuser.me/api/portraits/women/76.jpg
https://randomuser.me/api/portraits/men/39.jpg
https://randomuser.me/api/portraits/women/32.jpg
https://randomuser.me/api/portraits/women/48.jpg
https://randomuser.me/api/portraits/men/11.jpg
https://randomuser.me/api/portraits/women/9.jpg
https://randomuser.me/api/portraits/women/53.jpg
https://randomuser.me/api/portraits/men/11.jpg

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [53]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)     

get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Kenan Sezek,male,Bolu,Manisa,kenan.sezek@example.com,1986-06-02T22:22:25.047Z,https://randomuser.me/api/portraits/men/7.jpg
1,Volkan Saygıner,male,Denizli,Niğde,volkan.sayginer@example.com,1989-07-12T23:43:56.094Z,https://randomuser.me/api/portraits/men/18.jpg
2,Jeppe Jørgensen,male,Lemvig,Midtjylland,jeppe.jorgensen@example.com,1985-12-10T14:11:21.751Z,https://randomuser.me/api/portraits/men/86.jpg
3,Andrea Montero,female,Arrecife,Ceuta,andrea.montero@example.com,1988-12-03T20:31:17.384Z,https://randomuser.me/api/portraits/women/2.jpg
4,Brielle Clark,female,Deer Lake,New Brunswick,brielle.clark@example.com,1963-09-21T12:25:07.383Z,https://randomuser.me/api/portraits/women/65.jpg
5,Otacília Moura,female,Santa Cruz do Sul,Tocantins,otacilia.moura@example.com,1970-03-28T05:44:18.291Z,https://randomuser.me/api/portraits/women/46.jpg
6,Babür Düşenkalkar,male,Elazığ,Hakkâri,babur.dusenkalkar@example.com,1962-08-04T00:24:36.257Z,https://randomuser.me/api/portraits/men/19.jpg
7,Lena Bremnes,female,Svenevik,Nordland,lena.bremnes@example.com,1956-10-08T00:53:31.540Z,https://randomuser.me/api/portraits/women/46.jpg
8,Allie Cunningham,female,Limerick,Kerry,allie.cunningham@example.com,1958-02-04T10:58:16.381Z,https://randomuser.me/api/portraits/women/55.jpg
9,Charlie Stokkel,female,Nijeveen,Zuid-Holland,charlie.stokkel@example.com,1952-01-17T00:49:12.340Z,https://randomuser.me/api/portraits/women/57.jpg

In [55]:
df1 = pd.DataFrame(get_users())  
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Salvador Oliver,male,Rockhampton,Western Australia,salvador.oliver@example.com,1973-06-05T11:24:35.902Z,https://randomuser.me/api/portraits/men/2.jpg
1,Elijah Bergmann,male,Meldal,Akershus,elijah.bergmann@example.com,1963-06-21T10:54:01.408Z,https://randomuser.me/api/portraits/men/80.jpg
2,Antonio Hicks,male,Raleigh,Georgia,antonio.hicks@example.com,1984-12-08T15:59:47.041Z,https://randomuser.me/api/portraits/men/38.jpg
3,Chris Haugerud,male,Slettebrotane,Sogn og Fjordane,chris.haugerud@example.com,1946-09-19T15:30:23.592Z,https://randomuser.me/api/portraits/men/43.jpg
4,Eleanor Jackson,female,Mullingar,Leitrim,eleanor.jackson@example.com,1972-05-24T04:56:10.175Z,https://randomuser.me/api/portraits/women/30.jpg
5,Villads Sørensen,male,Ølstykke,Danmark,villads.sorensen@example.com,1978-03-22T03:36:30.836Z,https://randomuser.me/api/portraits/men/91.jpg
6,Virginia Moya,female,Ciudad Real,Castilla la Mancha,virginia.moya@example.com,1947-12-07T14:53:19.529Z,https://randomuser.me/api/portraits/women/84.jpg
7,Gökhan Babacan,male,Kayseri,Şanlıurfa,gokhan.babacan@example.com,1973-12-15T04:47:34.518Z,https://randomuser.me/api/portraits/men/84.jpg
8,Paul-Heinz Meißner,male,Garbsen,Hessen,paul-heinz.meissner@example.com,1948-06-10T19:10:48.419Z,https://randomuser.me/api/portraits/men/41.jpg
9,Minnie Shelton,female,Carrollton,Vermont,minnie.shelton@example.com,1986-07-08T05:49:29.876Z,https://randomuser.me/api/portraits/women/43.jpg

This last code line generated a _pandas_ dataframe that can be used for any testing purposes.

___

### Example 2

Another, more common way to use APIs, is through requests library. The next lab, Requests and HTTP, will contain more information about requests.

In [56]:
#Import required libraries
import requests
import json

In [57]:
#Obtain fuitvice API requests.get("url") function
data = requests.get("https://fruityvice.com/api/fruit/all")

#Retrieve results using json.loads() function
results = json.loads(data.text)

#Convert json data into panda df
pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
5,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
6,Prunus,Cherry,9,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
7,Vaccinium,Cranberry,87,Ericaceae,Ericales,"{'carbohydrates': 12.2, 'protein': 0.4, 'fat':..."
8,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,"{'carbohydrates': 9, 'protein': 9, 'fat': 1.5,..."
9,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
10,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."
11,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
12,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
13,Vitis,Grape,81,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
14,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
15,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,"{'carbohydrates': 14.6, 'protein': 1.14, 'fat'..."
18,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
19,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
21,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
24,Morus,Morus,82,Moraceae,Rosales,"{'carbohydrates': 9.8, 'protein': 1.44, 'fat':..."
25,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
26,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
28,Prunus,Peach,86,Rosaceae,Rosales,"{'carbohydrates': 9.5, 'protein': 0.9, 'fat': ..."
29,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
30,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
31,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
32,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,"{'carbohydrates': 7, 'protein': 1, 'fat': 0.4,..."
33,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
34,Punica,Pomegranate,79,Lythraceae,Myrtales,"{'carbohydrates': 18.7, 'protein': 1.7, 'fat':..."
35,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
36,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
37,Citrus,Tangerine,77,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 0, 'fat': 0...."
38,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
39,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [58]:
df2 = pd.json_normalize(results)
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.00,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
5,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
6,Prunus,Cherry,9,Rosaceae,Rosales,12.00,1.00,0.30,50,8.00
7,Vaccinium,Cranberry,87,Ericaceae,Ericales,12.20,0.40,0.10,46,4.00
8,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,9.00,9.00,1.50,60,8.00
9,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
10,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,8.00,0.60,0.40,44,3.00
11,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
12,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
13,Vitis,Grape,81,Vitaceae,Vitales,18.10,0.72,0.16,69,16.00
14,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
15,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,14.60,1.14,0.50,61,8.90
18,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
19,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
21,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
24,Morus,Morus,82,Moraceae,Rosales,9.80,1.44,0.39,43,8.10
25,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
26,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
28,Prunus,Peach,86,Rosaceae,Rosales,9.50,0.90,0.25,39,8.40
29,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
30,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
31,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
32,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,7.00,1.00,0.40,36,3.00
33,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
34,Punica,Pomegranate,79,Lythraceae,Myrtales,18.70,1.70,1.20,83,13.70
35,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
36,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
37,Citrus,Tangerine,77,Rutaceae,Sapindales,8.30,0.00,0.40,45,9.10
38,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
39,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

In [59]:
#For example, extract the info of the family and genus of a cherry
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0][3]) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

___

### Exercise 2

Find out how many calories are contained in a banana.

In [60]:
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

### Exercise 3

Access this [page](https://github.com/public-apis/public-apis#animals) that contains a list of free public APIs. Choose any of them and load/extract some info

In [61]:
#Load your data
data3 = requests.get("http://dog-api.kinduff.com/api/facts?number=10")

#Retrieve results using json.loads() function
results3 = json.loads(data3.text)

#Convert into pandas df
df3 = pd.DataFrame(results3)
df3

                                               facts  success
0  The world’s smartest dogs are thought to be (1...     True
1                     Dogs are natural pack animals.     True
2  The Border Collie, Poodle and Golden Retriever...     True
3  Apple and pear seeds contain arsenic, which ma...     True
4  The Newfoundland has a water-resistant coat an...     True
5  The phrase "raining cats and dogs" originated ...     True
6  In Iran, it is against the law to own a dog as...     True
7                        Dogs have no sense of time.     True
8  Chocolate contains a substance known as theobr...     True
9  Chase that tail! Dogs chase their tails for a ...     True

### End :)